// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaXcGmeWxTnJChQ4nRDA4KMzarEsti0qM',
    appId: '1:633767430031:web:21d5ebb2eed265977cedfa',
    messagingSenderId: '633767430031',
    projectId: 'smartflow-90170',
    authDomain: 'smartflow-90170.firebaseapp.com',
    storageBucket: 'smartflow-90170.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXDIZpz1__Ew-9dKAR409Nb1OvpbkK9aE',
    appId: '1:633767430031:android:bff429c63d03a1377cedfa',
    messagingSenderId: '633767430031',
    projectId: 'smartflow-90170',
    storageBucket: 'smartflow-90170.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9lwunLp_qRgIKmR7hTohGOTInstkdvuY',
    appId: '1:633767430031:ios:b12e882bdaca564b7cedfa',
    messagingSenderId: '633767430031',
    projectId: 'smartflow-90170',
    storageBucket: 'smartflow-90170.firebasestorage.app',
    iosBundleId: 'com.example.smartflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9lwunLp_qRgIKmR7hTohGOTInstkdvuY',
    appId: '1:633767430031:ios:b12e882bdaca564b7cedfa',
    messagingSenderId: '633767430031',
    projectId: 'smartflow-90170',
    storageBucket: 'smartflow-90170.firebasestorage.app',
    iosBundleId: 'com.example.smartflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaXcGmeWxTnJChQ4nRDA4KMzarEsti0qM',
    appId: '1:633767430031:web:90f47d9ee5f5adc37cedfa',
    messagingSenderId: '633767430031',
    projectId: 'smartflow-90170',
    authDomain: 'smartflow-90170.firebaseapp.com',
    storageBucket: 'smartflow-90170.firebasestorage.app',
  );
}
